### ISSUE TITLE
Bug: All lists do not show current day's transactions

### ISSUE THREAD

**Issue by robzor** [dispositiontools/craft-commerceinsights#8]
Hi there, sorry for the barrage of tickets!

By default, the date picker on all the report views is pre-filled with: From: 1st of current month -> To: Today's date.

But no transactions from today are shown, you have to manually change the date picker to 1 day higher, i.e. tomorrow.

(e.g. today is the 12th, but I have to select 13th to see today's transactions).

Could you take a look into this please when you have a second?

Thanks,

Rob

**Comment by dispositiontools** [comment]
Hmm. Thank you. I'll check in to this and get back to you. Thanks for all this feedback.

**Comment by robzor** [comment]
Hi there,

Here are some screenshots. If it helps I am in the UK GMT timezone if it has anything to do with that.

I made a test transaction yesterday (then refunded it). I've logged in to the CMS and selected 12th as the end date.

![CleanShot 2023-01-13 at 11 08 55](https://user-images.githubusercontent.com/704032/212306548-1fd289a2-b3f7-46ba-901d-3a9886452968.png)

I now update the end date to the 13th:

![CleanShot 2023-01-13 at 11 10 18](https://user-images.githubusercontent.com/704032/212306630-f019e3bd-23ff-4a23-82c5-eb342f78004c.png)

I'm on Craft 4.3.6.1 and Commerce 4.2.4

**Comment by dispositiontools** [comment]
Hi @robzor, 
thanks for your patience while I looked in to this - so this comes from a mental bug rather than a coding one - ie somewhere a long the line the idea of between two dates was between the start of the date of those two dates. 

For example show reports between 2023-01-01 00:00:00 and 2023-01-07 00:00:00, but obviously this doesn't make sense to how we all actually use this report. 

I'll make the update to fully include the end date, which does make much more sense. Thanks for this feedback.

**Comment by robzor** [comment]
Hi @dispositiontools thank you so much! The client is loving your plugin :)

**Comment by dispositiontools** [comment]
@robzor This has now been fixed with versions [4.0.3](https://github.com/dispositiontools/craft-commerceinsights/releases/tag/v4.0.3) and [v1.0.12](https://github.com/dispositiontools/craft-commerceinsights/releases/tag/v1.0.12). Thank you for your patience
