### ISSUE TITLE
Error best selling products

### ISSUE THREAD

**Issue by JoeriE** [dispositiontools/craft-commerceinsights#9]
I get an error when searching for the best selling products:
`Undefined index: product`

<img width="1091" alt="image" src="https://github.com/dispositiontools/craft-commerceinsights/assets/11161180/6a56df62-e123-4f6e-923b-4c5dfd85dcc0">

Best wishes

**Comment by dispositiontools** [comment]
HI @JoeriE 
On it. 

Will get back to you shortly

**Comment by dispositiontools** [comment]
Thanks for your patience @JoeriE. This has now been fixed with versions [4.0.3](https://github.com/dispositiontools/craft-commerceinsights/releases/tag/v4.0.3) and [v1.0.12](https://github.com/dispositiontools/craft-commerceinsights/releases/tag/v1.0.12)
Donations hadn't been taken properly into account, or line items with out products. I'm now working on a donation report to add to the suite.
